### ISSUE TITLE
Pitch: Enable Github Actions for ci testing

### ISSUE THREAD

**Issue by SusanDoggie** [apple/swift-numerics#60]
This also helps with performance tuning.

**Comment by ole** [comment]
+1. I think this is a good idea to quickly get a CI process running, unless there are plans to integrate Swift-Numerics into Swift's overall CI story. I recently set up GitHub actions for a SwiftPM package of mine and it turned out to be quite easy. You sign up for GitHub actions and add some config files to the repository.

[This is how the configuration looks in my package](https://github.com/ole/Ampere/tree/master/.github/workflows). Check out the [Actions tab](https://github.com/ole/Ampere/actions) to see how the CI reports look:

**Comment by stephentyrone** [comment]
https://github.com/apple/swift-numerics/commit/ee54cc207583f8b481d8ca3e7357819963c2be40

Nothing sophisticated, but wired up and working. I'd like to get the tests and benchmarks more mature before sinking too much effort into the workflows around them.

**Comment by natecook1000** [comment]
:shipit:
